added ALLOW_SECURE_COOKIES env variable
hoppscotch/docs pull request #217
Opened 2024-07-24 20:17 UTC by SanskritiHarmukh

- [x] Updated the environment file in Community and Enterprise Edition with new variable : ALLOW_SECURE_COOKIES

2024-07-24 20:26 UTC, balub requested changes

2024-07-24 20:26 UTC, balub commented on documentation/self-host/enterprise-edition/install-and-build.mdx
> +8. `ALLOW_SECURE_COOKIES` : Ensures that cookies are transmitted only over secure (HTTPS) connections.
```suggestion
8. `ALLOW_SECURE_COOKIES`: If disabled users will be able to use Hoppscotch over HTTP connections as well. It is recommended that this be left enabled as some auth providers may not work if this value is set to true.
```

2024-07-24 20:26 UTC, balub commented on documentation/self-host/community-edition/install-and-build.mdx
> +7. `ALLOW_SECURE_COOKIES` : Ensures that cookies are transmitted only over secure (HTTPS) connections.
```suggestion
7. `ALLOW_SECURE_COOKIES`: If disabled users will be able to use Hoppscotch over HTTP connections as well. It is recommended that this be left enabled as some auth providers may not work if this value is set to true.
```

2024-07-24 20:26 UTC, balub commented on documentation/features/widgets.mdx
I don't see how this change is relevant to the PR, please remove it from this PR.

2024-07-24 20:29 UTC, SanskritiHarmukh commented on documentation/features/widgets.mdx
Okay, I spotted it while going through docs, thus made changes in this PR itself.

2024-07-24 20:31 UTC, balub commented on documentation/features/widgets.mdx
I would suggest mentioning this in the PR desc or someplace else. I have no context regarding this change hence don't want to approve and have something possible wrong merged.

2024-07-24 20:40 UTC, SanskritiHarmukh commented on documentation/features/widgets.mdx
Sure, I have updated the description. Will ask Kiran to review.

2024-07-27 05:03 UTC, thetronjohnson approved these changes

2024-07-27 05:04 UTC, merged