v2024.8.0 Documentation Updates: AWS Signature Auth Method, Description field, Import HAR files
hoppscotch/docs pull request #232
Opened 2024-08-28 14:44 UTC by SanskritiHarmukh

This PR includes documentation related to the following:

- [x] AWS Signature under [Authorization Page](https://docs.hoppscotch.io/documentation/features/authorization).
- [x] Referenced description field under "[Using Parameters Tab](https://docs.hoppscotch.io/documentation/getting-started/rest/request-parameters#using-the-parameters-tab)" section.
- [x] Created a Request Headers page under "RESTful API" folder and included information about the description field there as well.
- [x] Added section for "Import from HAR" (Waiting for implementation on engineering end to verify the content here).

2024-08-28 16:54 UTC, jamesgeorge007 reviewed
- It might be helpful to mention the bulk edit mode existing under `Headers`, `Parameters` & `Variables` (out of scope) tabs, especially since we're adding a dedicated page for request headers.

- For headers derived from the `Authorization` type being set and inherited ones, the `description` field will appear disabled and the value will be populated for an inherited header if specified, leaving a note regarding the same might be useful.

2024-08-28 21:10 UTC, SanskritiHarmukh commented
> * It might be helpful to mention the bulk edit mode existing under `Headers`, `Parameters` & `Variables` (out of scope) tabs, especially since we're adding a dedicated page for request headers.
> * For headers derived from the `Authorization` type being set and inherited ones, the `description` field will appear disabled and the value will be populated for an inherited header if specified, leaving a note regarding the same might be useful.

Hey @jamesgeorge007, I have added the requested suggestions.

2024-08-29 09:12 UTC, thetronjohnson requested changes

2024-08-29 09:12 UTC, thetronjohnson commented on documentation/getting-started/rest/request-headers.mdx
The page is not rendering because `<Icon icon="pen-to-square" iconType="solid" />` is not imported, could you either do the import or remove this Component

2024-08-29 09:12 UTC, thetronjohnson commented on documentation/getting-started/rest/request-parameters.mdx
Same with the `<Icon icon="pen-to-square" iconType="solid" />` component in this page, it is not imported, could you either do the import or remove this Component

2024-08-29 09:42 UTC, SanskritiHarmukh commented on documentation/getting-started/rest/request-headers.mdx
@jamesgeorge007 , could you confirm if you are also facing this issue? I am unable to reproduce it on my end.
 
![Screenshot from 2024-08-29 14-48-07](https://github.com/user-attachments/assets/17d9309f-bb8d-4036-ad10-ce21e576285a)

2024-08-29 09:43 UTC, SanskritiHarmukh commented on documentation/getting-started/rest/request-parameters.mdx
Similarly for parameters,
![Screenshot from 2024-08-29 15-13-16](https://github.com/user-attachments/assets/2299bd1f-dead-4bd4-ac8b-39a7248e6cb7)

2024-08-29 10:58 UTC, jamesgeorge007 commented on documentation/getting-started/rest/request-headers.mdx
It's working on my end. [Icon](https://mintlify.com/docs/content/components/icons#icons) seems like a pre-available component like [Info](https://mintlify.com/docs/content/components/callouts#info-callouts) etc that can be used without importing.

2024-08-29 10:58 UTC, jamesgeorge007 commented on documentation/getting-started/rest/request-parameters.mdx
https://github.com/hoppscotch/docs/pull/232#discussion_r1735995523

2024-08-29 11:02 UTC, jamesgeorge007 approved these changes

2024-08-29 11:05 UTC, merged