Documentation addition related to v2024.9.0
hoppscotch/docs pull request #247
Opened 2024-09-25 21:02 UTC by SanskritiHarmukh

This PR includes the following updates:

- [x] Added a section for **Duplicating an Environment**, noting that secret variable values are not copied to the duplicated environment.
- [x] Updated the [Variables](https://docs.hoppscotch.io/documentation/features/variables) page to include Predefined Variables and marked their color identifier as yellow in the table.
- [x] Added a Digest Auth section to the [Authorization](https://docs.hoppscotch.io/documentation/features/authorization) page.
- [x] Removed the note stating, "Duplicating a collection is disabled in 'Personal Workspace' for the self-hosted instance."
- [x] Created a new Response page under the [RESTful API](https://docs.hoppscotch.io/documentation/getting-started/rest/creating-a-request) section, describing various parts of the interface.
- [x] Included steps for `Saving response as Example`.
- [x] Added a section for Importing from Personal and Other Cloud Workspaces.
- [ ] Import responses from external sources (Waiting for the implementation on engineering end.)

2024-09-30 05:06 UTC, thetronjohnson requested changes

2024-09-30 05:06 UTC, thetronjohnson commented on mint.json
Could you move `documentation/getting-started/rest/response-handling` to be the second page in the group RESTful APIs, right after `documentation/getting-started/rest/creating-a-request`

2024-09-30 05:21 UTC, SanskritiHarmukh commented on mint.json
will do

2024-09-30 05:40 UTC, thetronjohnson approved these changes

2024-10-04 09:10 UTC, liyasthomas approved these changes
LGTM

2024-10-04 09:10 UTC, merged